// Held items, one primitive list per HeldKind. Offsets are relative to the right-hand grip
// (`handGrip()`), +Y up and +Z forward, authored for an adult arm and scaled by `heldScale()`.
// Pure data — no three, no React.

import type { HeldKind } from "@shared/world";
import type { HumanoidPart } from "./humanoidParts";

export const HELD_SHAPE: Record<HeldKind, HumanoidPart[]> = {
  none: [],
  staff: [
    {
      id: "staff-shaft",
      geo: "cylinder",
      offset: [0, 0.34, 0],
      size: [0.045, 1.15, 0.045],
      rotation: [0, 0, 0],
      color: "wood",
      emissive: 0,
    },
    {
      id: "staff-orb",
      geo: "sphere",
      offset: [0, 0.94, 0],
      size: [0.16, 0.16, 0.16],
      rotation: [0, 0, 0],
      color: "glow",
      emissive: 2.2,
    },
  ],
  sword: [
    {
      id: "sword-grip",
      geo: "box",
      offset: [0, 0.02, 0],
      size: [0.05, 0.16, 0.05],
      rotation: [0, 0, 0],
      color: "dark",
      emissive: 0,
    },
    {
      id: "sword-guard",
      geo: "box",
      offset: [0, 0.11, 0],
      size: [0.22, 0.04, 0.07],
      rotation: [0, 0, 0],
      color: "accent",
      emissive: 0.5,
    },
    {
      id: "sword-blade",
      geo: "box",
      offset: [0, 0.46, 0],
      size: [0.08, 0.66, 0.025],
      rotation: [0, 0, 0],
      color: "metal",
      emissive: 0,
    },
  ],
  lantern: [
    {
      id: "lantern-bail",
      geo: "box",
      offset: [0, -0.04, 0],
      size: [0.02, 0.12, 0.02],
      rotation: [0, 0, 0],
      color: "metal",
      emissive: 0,
    },
    {
      id: "lantern-case",
      geo: "box",
      offset: [0, -0.18, 0],
      size: [0.15, 0.18, 0.15],
      rotation: [0, 0, 0],
      color: "metal",
      emissive: 0,
    },
    {
      id: "lantern-core",
      geo: "sphere",
      offset: [0, -0.18, 0],
      size: [0.11, 0.13, 0.11],
      rotation: [0, 0, 0],
      color: "glow",
      emissive: 2.6,
    },
  ],
  basket: [
    {
      id: "basket-body",
      geo: "cylinder",
      offset: [0, -0.16, 0.06],
      size: [0.32, 0.22, 0.32],
      rotation: [0, 0, 0],
      color: "wood",
      emissive: 0,
    },
    {
      id: "basket-rim",
      geo: "cylinder",
      offset: [0, -0.05, 0.06],
      size: [0.35, 0.04, 0.35],
      rotation: [0, 0, 0],
      color: "cloth",
      emissive: 0,
    },
  ],
  scroll: [
    {
      id: "scroll-tube",
      geo: "cylinder",
      offset: [0, 0.02, 0.07],
      size: [0.09, 0.34, 0.09],
      rotation: [0, 0, Math.PI / 2],
      color: "cloth",
      emissive: 0,
    },
    {
      id: "scroll-cap-left",
      geo: "cylinder",
      offset: [-0.17, 0.02, 0.07],
      size: [0.06, 0.05, 0.06],
      rotation: [0, 0, Math.PI / 2],
      color: "accent",
      emissive: 0.3,
    },
    {
      id: "scroll-cap-right",
      geo: "cylinder",
      offset: [0.17, 0.02, 0.07],
      size: [0.06, 0.05, 0.06],
      rotation: [0, 0, Math.PI / 2],
      color: "accent",
      emissive: 0.3,
    },
  ],
  hammer: [
    {
      id: "hammer-haft",
      geo: "cylinder",
      offset: [0, 0.2, 0],
      size: [0.05, 0.62, 0.05],
      rotation: [0, 0, 0],
      color: "wood",
      emissive: 0,
    },
    {
      id: "hammer-head",
      geo: "box",
      offset: [0, 0.52, 0],
      size: [0.22, 0.16, 0.17],
      rotation: [0, 0, 0],
      color: "metal",
      emissive: 0,
    },
    {
      id: "hammer-band",
      geo: "box",
      offset: [0, 0.52, 0],
      size: [0.23, 0.05, 0.18],
      rotation: [0, 0, 0],
      color: "accent",
      emissive: 0.4,
    },
  ],
  bow: [
    {
      id: "bow-limb",
      geo: "arc",
      offset: [0, 0.16, 0],
      size: [0.92, 0.92, 0.92],
      rotation: [0, Math.PI / 2, -Math.PI * 0.375],
      color: "wood",
      emissive: 0,
    },
    {
      id: "bow-string",
      geo: "box",
      offset: [0, 0.16, 0.16],
      size: [0.01, 0.78, 0.01],
      rotation: [0, 0, 0],
      color: "cloth",
      emissive: 0,
    },
    {
      id: "bow-nock",
      geo: "sphere",
      offset: [0, 0.16, 0.16],
      size: [0.05, 0.05, 0.05],
      rotation: [0, 0, 0],
      color: "accent",
      emissive: 0.6,
    },
  ],
  fan: [
    {
      id: "fan-leaf",
      geo: "wedge",
      offset: [0, 0.2, 0.06],
      size: [0.5, 0.02, 0.5],
      rotation: [1.1, 0.4, 0],
      color: "cloth",
      emissive: 0,
    },
    {
      id: "fan-rib",
      geo: "box",
      offset: [0, 0.07, 0.02],
      size: [0.03, 0.16, 0.03],
      rotation: [0, 0, 0],
      color: "accent",
      emissive: 0.3,
    },
  ],
  lute: [
    {
      id: "lute-belly",
      geo: "sphere",
      offset: [0, -0.06, 0.04],
      size: [0.3, 0.34, 0.2],
      rotation: [0, 0, 0],
      color: "wood",
      emissive: 0,
    },
    {
      id: "lute-neck",
      geo: "box",
      offset: [0.06, 0.24, 0.04],
      size: [0.06, 0.48, 0.05],
      rotation: [0, 0, -0.22],
      color: "dark",
      emissive: 0,
    },
    {
      id: "lute-strings",
      geo: "box",
      offset: [0.03, 0.08, 0.13],
      size: [0.07, 0.42, 0.01],
      rotation: [0, 0, -0.22],
      color: "accent",
      emissive: 0.5,
    },
  ],
  spear: [
    {
      id: "spear-shaft",
      geo: "cylinder",
      offset: [0, 0.4, 0],
      size: [0.04, 1.5, 0.04],
      rotation: [0, 0, 0],
      color: "wood",
      emissive: 0,
    },
    {
      id: "spear-tip",
      geo: "cone",
      offset: [0, 1.24, 0],
      size: [0.12, 0.28, 0.12],
      rotation: [0, 0, 0],
      color: "metal",
      emissive: 0,
    },
    {
      id: "spear-collar",
      geo: "cylinder",
      offset: [0, 1.08, 0],
      size: [0.08, 0.05, 0.08],
      rotation: [0, 0, 0],
      color: "accent",
      emissive: 0.5,
    },
  ],
};
