// Generated by scripts/generate-asset-hashes.mjs from the actual renderer recipes.
export const BUILTIN_ASSET_HASHES = {
  tree: "sha256:939925faa4cfc6a7f3090a6777c2e5c8a854a1a9f7816a188ea707e408db37fd",
  rock: "sha256:d7fb17770c12911b92acb5d08b0358819210933bf806203e9be9fa44e33796e2",
  torch: "sha256:1605503f6d10ee31195cb9344e6b23bfd6e96879d1402343c4f08ecab1ce6e4c",
  crate: "sha256:bc6f7a2c8c42cf4580bd4cd24f75835f1ac2b21ddeda4569a30adaef85ee48f1",
  altar: "sha256:70d1db3927cc9b52ba584cb7e0b7dd41f206a9c0fed94f927d6d7ba2d2d474b1",
  well: "sha256:3c276fc6340fb6bd16522fafdf29d156f6c21330555987f4ea52ab6f40e0197d",
  statue: "sha256:7d24097a430b4e577d726d927e7ca903759365d8baeb54f2bd02f7aff6499e08",
  pillar: "sha256:6a1a1c5628bbed198a5f6795c3ff20a44b53dde7e910640bbfcd6cac5d33f8b4",
  fence: "sha256:4a76e1ed161f693563b36ee277abf6ee64edb64d7a4d7aa726527442c404d032",
  flower: "sha256:5860b9c8179bc8edba82dde4601438acb68d92d56a8d384e7b214ea5898d492a",
  mushroom: "sha256:d3d423a674e7a905188f18e805918b147795d7842d70efb6e16b22b4be3922b4",
  signpost: "sha256:105a289343a23d5271adc4a884dd729d1faec5f1487391c7486dd50a4da4b72d",
  machine_gear: "sha256:f95e8bb5d94d6d7379678c672c5027002520ffc5df558666fa042b9a5805a802",
  conveyor: "sha256:5b6bf31cc32daf56067f27ffea5544f80ffb0633d960c4e2b277109998cde985",
  boiler: "sha256:87b7c165bff68b9d60c3805f7a13f030c2f330c48f8f3887d64229facdaee3ec",
  pipe_stack: "sha256:b6c29968d760f722ebcb8ee2c269495f182ebb201a6afc74cefc8582b3aad370",
  crane: "sha256:486892960b81632492f3309014c4bf89fea595fabb7a2eaa2548995ee0e22ee4",
  reactor: "sha256:87a0df33367511fb8ea43581e377319c5af06d0843c50d06137ab381ef31068b",
  // Countryside kinds (plan.md P2). Hashed with the same recipe function, appended by hand: the pack
  // hash below is pinned by every installed v2 cartridge, so it keeps naming the 1.0.0 pack.
  utility_pole: "sha256:fade0e73b446f5319b740f7d88fee71caf905c5ee97d5b16a9bba75aef10f3a9",
  vending_machine: "sha256:147aa6ea59afcbaa4e42900fdd5560b4931aaf8d2a8312d3039e94963e9c7062",
  bus_stop: "sha256:c367cdb04635f0cfa443c849cd19243ba9643b8a62fae82a303c18c0a282bc93",
  rail_track: "sha256:8f307f26a67a8167956effb835b2810cf8070e61a1fdee00748857481803f4b1",
  chimney: "sha256:cbf7c16efe2169d001cec1aa4dae8df9dd0081cba5f21bc13326a34d9e306e3d",
  steel_tower: "sha256:8524e32e1b9a8e7552c5e566bbc455734de0f2c67906e8d41fabe8419045b981",
  windmill: "sha256:f4438c7e86b91795150c55cbb5239479e6cd4420620abe08fb8468c22188fad2",
  breakwater: "sha256:dc88e9ffda2bd9ef25164267663219f443719b50afc6fff8930488ad9eef9ed2",
  house: "sha256:0e05bd8be25499d3a3afe5721d45662b63f6e1ba24d86f8e24018925848520dd",
} as const;
export const BUILTIN_PACK_HASH =
  "sha256:95794c98e137730b9b0e13ac33db77425a667c8c738de329a3295e167e42b8f9" as const;
